#!/bin/bash
#
# Copyright (C) 2012-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Fixture for tests involving 'morph build'

source "$SRCDIR/scripts/fix-committer-info"

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch test:morphs branch1
"$SRCDIR/scripts/test-morph" edit linux-system linux-stratum linux

# Fix UUID's in the checked out repos to make build branch names deterministic
git config -f "$DATADIR/workspace/branch1/.morph-system-branch/config" \
    branch.uuid 123456789
git config -f "$DATADIR/workspace/branch1/test/morphs/.git/config" \
    morph.uuid 987654321
git config -f "$DATADIR/workspace/branch1/test/kernel-repo/.git/config" \
    morph.uuid AABBCCDDE

