#!/bin/sh
#
# Run test suite for morph.
#
# Copyright (C) 2011, 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

python setup.py clean check
cmdtest tests
cmdtest tests.branching
if [ $(whoami) = root ] && command -v mkfs.btrfs > /dev/null
then
    cmdtest tests.as-root
fi

if [ -d .git ];
then
    echo "Checking copyright statements"
    git ls-files | xargs scripts/check-copyright-year
    
    echo 'Checking source code for silliness'
    git ls-files |
    grep -v '\.gz$' |
    grep -Ev 'tests[^/]*/.*\.std(out|err)' |
    while read x
    do
        if tr -cd '\t' < "$x" | grep . > /dev/null
        then
            echo "ERROR: $x contains TAB characters" 1>&2
            errors=1
        fi

        case "$x" in
            baserock-bootstrap)
                ;;
            *)
                if awk 'length > 79' "$x" | grep . > /dev/null
                then
                    echo "ERROR: $x has lines longer than 79 chars" 1>&2
                    errors=1
                fi
                ;;
        esac
    done
fi
exit $errors
