#!/usr/bin/python
#
# WARNING: THIS IS HIGHLY EXPERIMENTAL CODE RIGHT NOW. JUST PROOF OF CONCEPT.
# DO NOT RUN UNTIL YOU KNOW WHAT YOU ARE DOING.
# 
# Copyright (C) 2011  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import cliapp
import json
import logging
import os
import shutil
import tempfile

import morphlib


class Morph(cliapp.Application):

    def add_settings(self):
        self.settings.boolean(['verbose', 'v'], 'show what is happening')
        self.settings.string(['git-base-url'],
                             'prepend URL to git repos that are not URLs',
                             metavar='URL')
        self.settings.string(['cachedir'], 
                             'put build results in DIR (default: %default)',
                             metavar='DIR', default='.')
        self.settings.boolean(['no-ccache'], 'do not use ccache')
        self.settings.boolean(['no-distcc'], 'do not use distcc')
        self.settings.integer(['max-jobs'], 
                              'run at most N parallel jobs with make (default '
                                'is to a value based on the number of CPUs '
                                'in the machine running morph',
                              metavar='N',
                              default=0)
        self.settings.boolean(['keep-path'], 
                              'do not touch the PATH environment variable '
                                '(use with tests ONLY)')
        self.settings.boolean(['bootstrap'], 
                              'build stuff in bootstrap mode; this is '
                                'DANGEROUS and will install stuff on your '
                                'system')

    def cmd_build(self, args):
        tempdir = morphlib.tempdir.Tempdir()
        builder = morphlib.builder.Builder(tempdir, self)

        if not os.path.exists(self.settings['cachedir']) and os.getuid() != 0:
            os.mkdir(self.settings['cachedir'])

        while len(args) >= 3:
            repo, ref, filename = args[:3]
            args = args[3:]
            self.msg('Building %s - %s - %s' % (repo, ref, filename))
            builder.build(repo, ref, filename)
        
        tempdir.remove()

        if args:
            raise cliapp.AppException('Extra args on command line: %s' % args)
            

    def msg(self, msg):
        '''Show a message to the user about what is going on.'''
        logging.debug(msg)
        if self.settings['verbose']:
            self.output.write('%s\n' % msg)
            self.output.flush()


if __name__ == '__main__':
    Morph().run()
