#!/bin/sh
#
# Copyright (C) 2011-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## 'bootstrap' mode is similar to 'test' mode, but they should not be included
## in the final stratum artifact. This feature is used to bootstrap the
## build-essential stratum using the toolchain of the host.

set -eu

# Create a fake 'compiler' chunk to go into build-essential stratum
"$SRCDIR/tests.build/setup-build-essential"

"$SRCDIR/scripts/test-morph" build-morphology \
    test:morphs-repo master hello-system

cd "$DATADIR/cache/artifacts"
echo "build-essential strata:"
for stratum in $(find . -regex '.*\.stratum\.build-essential-[^.]*$' | sort)
do
    echo "$stratum"
    sed 's/[a-f0-9]\{64\}/xxxx/g' "$stratum"
    echo
done
echo
echo "hello-system:"
system=$(ls *hello-system-rootfs)
tar tf "$system" | LC_ALL=C sort -u | sed '/^\.\/./s:^\./::' \
    | grep -v '^baserock'
