#!/bin/sh
#
# Copyright (C) 2012-2013  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Test that the autotools build system fails if it runs autogen.sh and that
## fails.

set -eu

cd "$DATADIR/chunk-repo"
git checkout -q farrokh

cat <<EOF > autogen.sh
#!/bin/sh
echo "in failing autogen.sh"
exit 1
EOF
chmod a+x autogen.sh

git add autogen.sh
git rm -q hello.morph
git commit -q -m "Convert hello to a broken autotools project"

"$SRCDIR/scripts/test-morph" build-morphology \
    test:morphs-repo master hello-system \
    >/dev/null 2> /dev/null

