#!/bin/bash
#
# Copyright (C) 2013,2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


# Test "morph cross-bootstrap", up to the point of the tarball it generates
# for the target

set -eu

"$SRCDIR/tests.build/setup-build-essential"

"$SRCDIR/scripts/test-morph" cross-bootstrap \
    $("$SRCDIR/scripts/test-morph" print-architecture) \
    test:morphs-repo master hello-system
