#!/bin/sh
#
# Copyright (C) 2013-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -eu

morphsrepo="$DATADIR/morphs-repo"
cd "$morphsrepo"

git checkout --quiet -b empty-stratum

# Create empty stratum to test S4585
cat <<EOF > hello-stratum.morph
name: hello-stratum
kind: stratum
EOF
sed -i 's/master/empty-stratum/' hello-system.morph
git add hello-stratum.morph hello-system.morph

git commit --quiet -m "add empty stratum"

"$SRCDIR/scripts/test-morph" build-morphology \
    test:morphs-repo empty-stratum hello-system
