#!/bin/sh
#
# Copyright (C) 2013,2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


## Morph should refuse build a chunk out of the context. Only
## system and stratum morphologies can be built.

set -eu

! "$SRCDIR/scripts/test-morph" build-morphology \
    test:morphs-repo master hello-stratum

! "$SRCDIR/scripts/test-morph" build-morphology \
    test:chunk-repo farrokh hello

