#!/bin/sh
#
# Copyright (C) 2011-2013,2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


## Test that temporary directories are created in the dir specified
## by --tempdir rather than specified in the environment by TMPDIR.

set -eu
export TMPDIR
TMPDIR="$DATADIR"/unwritable-tmp
install -m 000 -d "$TMPDIR"
mkdir "$DATADIR"/tmp
"$SRCDIR/scripts/test-morph" build-morphology --tempdir "$DATADIR"/tmp \
    test:morphs-repo master hello-system
