#!/bin/sh
#
# Copyright (C) 2011, 2012, 2013, 2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


set -eu

# Disable test on versions of Python before 2.7.
. "$SRCDIR/scripts/python-check"

cache="$DATADIR/cache/artifacts"

arch=$("$SRCDIR/scripts/test-morph" print-architecture)

cd "$DATADIR/kernel-repo"
cat <<EOF >linux.morph
name: linux
kind: chunk
install-commands:
  - mkdir -p "\$DESTDIR/boot"
  - touch "\$DESTDIR/boot/zImage"
EOF
git add linux.morph
git commit --quiet -m 'Make the kernel create a dummy zImage'

"$SRCDIR/scripts/test-morph" \
    build-morphology test:morphs master linux-system > /dev/null

for suffix in kernel rootfs
do
    if [ ! -e "$cache"/*system.linux-system-$suffix ]
    then
        echo "can't find $cache/*system.linux-system-$suffix" 1>&2
        find "$cache" 1>&2
        exit 1
    fi
done
