#!/bin/bash
#
# Copyright (C) 2011, 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## A system kind of syslinux-disk should create the disk image, plus a kernel
## file.

set -eu

. "$SRCDIR/tests.as-root/lib"

# We only support x86 systems with syslinux-disk.
arch=$(uname -m)
case "$arch" in
    x86*) ;;
    *) exit 0 ;;
esac

cache="$DATADIR/cache/artifacts"

rootfs=$("$SRCDIR/scripts/test-morph" --find-system-artifact \
    build-morphology test:morphs master linux-system)

for suffix in kernel rootfs
do
    if [ ! -e "$cache"/*system.linux-system-"$suffix" ];
    then
        echo "No .system.linux-system-$suffix" 1>&2
        find "$cache" 1>&2
        exit 1
    fi
done

mkdir -p "$DATADIR/mnt"
device=$(loopback_rootfs "$rootfs")
mount "$device" "$DATADIR/mnt"
trap 'cd /; umount -d "$device"' INT TERM ERR

cd "$DATADIR/mnt"
find | LC_ALL=C sort -u
sed -e 's/ on [0-9\-]\+//' "$DATADIR/mnt/factory-run/etc/os-release"
cd "$DATADIR"
umount -d "$device"
