#!/bin/sh
#
# Copyright (C) 2011, 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# Handle invalid syslinux MBR parameters.

set -eu

# We only support x86 systems with syslinux-disk.
arch=$(uname -m)
case "$arch" in
    x86*) ;;
    *) exit 0 ;;
esac

cache="$DATADIR/cache/artifacts"

"$SRCDIR/scripts/test-morph" --syslinux-mbr-search-path=nosuchfile.bin \
    build-morphology test:morphs master linux-system > /dev/null
