#!/bin/sh
#
# A system kind of 'rootfs-tarball' should create a tarball containing
# all the required files
#
# Copyright (C) 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -eu

case $(python --version 2>&1) in
    "Python 2.6"*) exit 0 ;;
esac

. "$SRCDIR/scripts/fix-committer-info"

tar=$("$SRCDIR/morph" \
        --no-default-config --config="$DATADIR/morph.conf" --verbose \
    build-morphology test:morphs-repo tarball-links hello-tarball 2>&1 |
    grep "system hello-tarball-rootfs is cached at" |
    sed -nre "s/^.*system hello-tarball-rootfs is cached at (\S+)$/\1/p")

extracted="$DATADIR/extracted"
mkdir -p "$extracted"
cd "$extracted"
tar -xf "$tar"
find . -mindepth 1 | LC_ALL=C sort -u | xargs ls -dF
