#!/bin/bash
#
# Copyright (C) 2012-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

## Some contents of morphologies (description, build-depends, chunks)
## should not change the cache keys of those morphs because they are
## either already considered (build-depends and chunks) or do not affect
## building (description). This test checks that changes to these parts
## of a morphology do not force rebuilds.

# FIXME: This seems to break because the new "morph edit" makes correct
# changes to build-dependencies, which breaks the old "morph build".
# Disable test now, re-enable it after "morph build" is fixed. --liw
exit 0

set -eu

source "$SRCDIR/tests.as-root/setup-build"

# Build once.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" build linux-system
ARTIFACT_COUNT="$(ls "$DATADIR/cache/artifacts" | wc -l)"

# Petrify the refs, so the morphologies will be different
(set -e && cd branch1/test/morphs && git push --quiet origin HEAD)
(set -e && cd branch1/test/kernel-repo && git push --quiet origin HEAD)
"$SRCDIR/scripts/test-morph" petrify

# Build with the petrified morphologies.
"$SRCDIR/scripts/test-morph" build linux-system
[ "$ARTIFACT_COUNT" -eq $(ls "$DATADIR/cache/artifacts" | wc -l) ]
