#!/bin/sh
#
# Test that the autotools build system fails if it runs autogen.sh and that
# fails.
#
# Copyright (C) 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


set -eu

x="$DATADIR/autogen-chunk"
mkdir "$x"
cat <<EOF > "$x/autogen.sh"
#!/bin/sh
echo "in failing autogen.sh"
exit 1
EOF
chmod a+x "$x/autogen.sh"
"$SRCDIR/scripts/run-git-in" "$x" init --quiet
"$SRCDIR/scripts/run-git-in" "$x" add .
"$SRCDIR/scripts/run-git-in" "$x" commit --quiet -m initial

"$SRCDIR/scripts/test-morph" build test:autogen-chunk master detected.morph \
   >/dev/null 2> /dev/null

