#!/bin/sh
#
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## When there are two chunks with the same "name" set in the morphology,
## only the first built should be used. This can cause build failures when
## the wrong name is set and could be a vector for including dodgy data in
## a system.

set -eu

( cd "$DATADIR/chunk-repo"
  git checkout --quiet farrokh
  cat >goodbye <<EOF
#!/bin/sh
echo Goodbye world, muahahahaha
EOF
  git add goodbye

  # add a morph with the same "name" but different commands
  cat >goodbye.morph <<EOF
{
    "name": "hello",
    "kind": "chunk",
    "build-system": "dummy",
    "install-commands": [
        "install -d \\"\$DESTDIR\\"/bin",
        "install goodbye \\"\$DESTDIR\\"/bin/hello"
    ]
}
EOF
  git add goodbye.morph

  git commit --quiet -m "add a totally safe script"
)

# build the dodgy chunk
"$SRCDIR/scripts/test-morph" build-morphology \
    test:chunk-repo farrokh goodbye

# build a stratum 
"$SRCDIR/scripts/test-morph" build-morphology \
    test:morphs-repo master hello-stratum

# unpack it and check the contents
INSTDIR="$DATADIR"/unpack
mkdir -p "$INSTDIR"
"$SRCDIR/scripts/assemble-stratum" --cachedir "$DATADIR/cache" \
                                   "$DATADIR/cache/artifacts/"*hello-stratum \
                                   "$DATADIR/stratum.tar" hello-stratum
tar -C "$INSTDIR" -xhf "$DATADIR/stratum.tar"
test "$("$INSTDIR"/bin/hello)" = "hello, world"
