#!/bin/sh
#
# If a stratum has symbolic links pointing to files, then the symlink
# should be removed and replaced by that file
#
# Copyright (C) 2011, 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -eu

cache="$DATADIR/cache/artifacts"

"$SRCDIR/scripts/test-morph" \
    build test:morphs-repo overlap overlap-stratum.morph
(cd "$cache" && for f in *.stratum.overlap-stratum; do tar -tvf "$f"; done |
 sed 's/^\(\S*\)[^.]*\./\1 /' | LC_ALL=C sort) | grep '/usr -> /'
