#!/bin/sh
#
# If a stratum has multiple chunks that have the same files in them,
# then this should be notified
#
# Copyright (C) 2011, 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -eu

cache="$DATADIR/cache/artifacts"
chunkrepo="$DATADIR/chunk-repo"
morphsrepo="$DATADIR/morphs-repo"
log="$DATADIR/morph.log"

cd "$morphsrepo"
git checkout --quiet -b overlap master
cat <<EOF >overlap-stratum.morph
{
  "name": "overlap-stratum",
  "kind": "stratum",
  "sources": [
    {
      "name": "overlap-foo-baz",
      "repo": "test:chunk-repo",
      "ref": "overlap"
    },
    {
      "name": "overlap-foobar",
      "repo": "test:chunk-repo",
      "ref": "overlap"
    },
    {
      "name": "overlap-fooqux",
      "repo": "test:chunk-repo",
      "ref": "overlap"
    }
  ]
}
EOF
git add overlap-stratum.morph
git commit --quiet -m "add overlapping stratum"

cd "$chunkrepo"
git checkout --quiet -b overlap master
cat <<EOF >overlap-foo-baz.morph
{
  "name": "overlap-foo-baz",
  "kind": "chunk",
  "install-commands": [
    "mkdir -p \$DESTDIR/bin",
    "for f in foo bar baz; do echo echo \$f >\$DESTDIR/bin/\$f; done"
  ]
}
EOF

cat <<EOF >overlap-foobar.morph
{
  "name": "overlap-foobar",
  "kind": "chunk",
  "install-commands": [
    "mkdir -p \$DESTDIR/usr/bin \$DESTDIR/bin",
    "echo echo foobar >\$DESTDIR/usr/bin/foobar",
    "ln -s /usr/bin/foobar \$DESTDIR/bin/foo",
    "ln -s /usr/bin/foobar \$DESTDIR/bin/bar"
  ]
}
EOF

cat <<EOF >overlap-fooqux.morph
{
  "name": "overlap-fooqux",
  "kind": "chunk",
  "install-commands": [
    "mkdir -p \$DESTDIR/usr/bin \$DESTDIR/bin",
    "for f in qux fooqux; do echo echo \$f >\$DESTDIR/usr/bin/\$f; done",
    "ln -s /usr/bin/fooqux \$DESTDIR/bin/foo"
  ]
}
EOF
git add overlap-*.morph

git commit --quiet -m 'Add overlapping chunks'

"$SRCDIR/scripts/test-morph" \
    build --verbose --log=$log test:morphs-repo overlap overlap-stratum.morph
grep WARNING $log | sed 's/^.*WARNING/WARNING/'
(cd "$cache" && ls *.chunk.*  *.stratum.* | sed 's/^[^.]*\./ /' | 
 LC_ALL=C sort)
