#!/bin/bash
#
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Test that 'morph update-gits' caches all the submodules needed by
## a chunk.

set -eu

# Local repos do not get cached, so we need to fake some remote repositories
git daemon --port=9419 --pid-file="$DATADIR/git.pid" --reuseaddr \
    --export-all --base-path="$DATADIR" 2> /dev/null &
trap 'kill $(cat "$DATADIR/git.pid")' INT TERM ERR
REPO_ALIAS='test=git://localhost:9419/%s#git://localhost:9419/%s'

# Create a repo to use as a submodule
submodule="$DATADIR/submodule-repo"
"$SRCDIR/scripts/cmd-filter" git init --quiet "$submodule"
"$SRCDIR/scripts/run-git-in" "$submodule" commit --quiet --allow-empty \
                                          --allow-empty-message -m ""
# Create an empty commit in a chunk repository
chunkrepo="$DATADIR/chunk-repo"
"$SRCDIR/scripts/run-git-in" "$chunkrepo" checkout --quiet farrokh
"$SRCDIR/scripts/run-git-in" "$chunkrepo" submodule --quiet add "$submodule" \
    > /dev/null
"$SRCDIR/scripts/run-git-in" "$chunkrepo" commit --quiet -m "add submodule"

"$SRCDIR/scripts/test-morph" --repo-alias=$REPO_ALIAS update-gits \
    test:morphs-repo master hello-stratum

kill $(cat "$DATADIR/git.pid")

test -d "$DATADIR/cache/gits/"*chunk?repo* && echo chunk-repo cached
test -d "$DATADIR/cache/gits/"*morphs?repo* && echo morphs-repo cached
test -d "$DATADIR/cache/gits/"*submodule?repo* && echo submodule-repo cached
