#!/bin/sh
#
# Copyright (C) 2013-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Test the workflow of adding a new chunk to a stratum then editing it

set -eu

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch test:morphs "me/add-then-edit"

cd "me/add-then-edit"

# add a chunk
cd test/morphs

python -c 'import yaml
with open("hello-stratum.morph", "r") as f:
    stratum = yaml.load(f)
stratum["chunks"].append({
    "build-depends": [],
    "name": "goodbye",
    "ref": "master",
    "repo": "test:goodbye",
})
with open("hello-stratum.morph", "w") as f:
    yaml.dump(stratum, f)
'

"$SRCDIR/scripts/test-morph" edit goodbye

# check whether the stratum still contains the goodbye chunk
grep -qFe goodbye hello-stratum.morph

# check whether edit has cloned the repository to the right branch
git --git-dir="../goodbye/.git" rev-parse --abbrev-ref HEAD
