#!/bin/bash
#
# Copyright (C) 2012,2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Make sure "morph branch" works anywhere in a workspace or system branch.

set -eu

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init

# First, create a branch.
"$SRCDIR/scripts/test-morph" branch test:morphs branch1

echo "Workspace after creating the first branch:"
"$SRCDIR/scripts/list-tree" "$DATADIR/workspace" | grep -v '/\.git/' |
    sed 's,/cache/gits/file_[^/]*_,/cache/gits/file_,' |
    grep -v 'cache/gits/file_[^/]*/'

# Now, create a nother branch from the workspace.
"$SRCDIR/scripts/test-morph" branch test:morphs branch2

echo "Workspace after creating the second branch:"
"$SRCDIR/scripts/list-tree" "$DATADIR/workspace" | grep -v '/\.git/' |
    sed 's,/cache/gits/file_[^/]*_,/cache/gits/file_,' |
    grep -v 'cache/gits/file_[^/]*/'

# Now, enter the first branch and create a third branch, which
# should not be created in the working directory but in the
# workspace directory.
cd "$DATADIR/workspace/branch1"
"$SRCDIR/scripts/test-morph" branch test:morphs branch3

echo "Workspace after creating the third branch:"
"$SRCDIR/scripts/list-tree" "$DATADIR/workspace" | grep -v '/\.git/' |
    sed 's,/cache/gits/file_[^/]*_,/cache/gits/file_,' |
    grep -v 'cache/gits/file_[^/]*/'

# Now, go into the morphs repository of that third branch and
# create a fourth system branch from in there. This, too, should
# end up being created in the toplevel workspace directory.
cd "$DATADIR/workspace/branch3/test/morphs"
"$SRCDIR/scripts/test-morph" branch test:morphs branch4

echo "Workspace after creating the fourth branch:"
"$SRCDIR/scripts/list-tree" "$DATADIR/workspace" | grep -v '/\.git/' |
    sed 's,/cache/gits/file_[^/]*_,/cache/gits/file_,' |
    grep -v 'cache/gits/file_[^/]*/'
