#!/bin/sh
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Make sure "morph branch" fails if the system branch already exists in the
# branch root (morphologies repo).

set -eu

cd "$DATADIR/morphs"
git checkout --quiet -b baserock/existing-branch

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init

# We create a valid branch inside the same prefix first so we can check it
# doesn't get caught up in the deletion of the invalid branch directory

"$SRCDIR/scripts/test-morph" branch test:morphs baserock/new-branch

[ -d "$DATADIR/workspace/baserock/new-branch" ]

"$SRCDIR/scripts/test-morph" branch test:morphs \
    baserock/existing-branch || true

[ -d "$DATADIR/workspace/baserock/new-branch" ]
[ ! -d "$DATADIR/workspace/baserock/existing-branch" ]
