#!/bin/bash
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# Verify that "morph checkout" works with repos that are not aliased.
# This test in particular verifies that URI schemes are stripped off
# and that the .git suffix is only removed at the end if it is actually
# present.


set -eu


REPO_WITH_SUFFIX="file://$DATADIR/morphs.git"
REPO_WITHOUT_SUFFIX="file://$DATADIR/morphs"

TEMP_DIR=$(dirname "$DATADIR")

cd "$DATADIR/workspace"

"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" checkout "$REPO_WITH_SUFFIX" master

echo "File tree of repo with suffix:"
"$SRCDIR/scripts/list-tree" . | grep -v '/\.git/' |
    sed 's,/cache/gits/file_[^/]*_,/cache/gits/file_,' |
    grep -v 'cache/gits/file_[^/]*/' |
    sed "s,${DATADIR:1},DATADIR,g" |
    sed "s,${TEMP_DIR:1},TEMP_DIR,g"

echo "Current branches of repo with suffix:"
"$SRCDIR/scripts/run-git-in" master/"${DATADIR:1}"/morphs branch

cd "$DATADIR"
rm -rf "$DATADIR/workspace"
mkdir "$DATADIR/workspace"
cd "$DATADIR/workspace"

"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" checkout "$REPO_WITHOUT_SUFFIX" master

echo "File tree of repo without suffix:"
"$SRCDIR/scripts/list-tree" . | grep -v '/\.git/' |
    sed 's,/cache/gits/file_[^/]*_,/cache/gits/file_,' |
    grep -v 'cache/gits/file_[^/]*/' |
    sed "s,${DATADIR:1},DATADIR,g" |
    sed "s,${TEMP_DIR:1},TEMP_DIR,g"

echo "Current branches of repo without suffix:"
"$SRCDIR/scripts/run-git-in" master/"${DATADIR:1}"/morphs branch
