#!/bin/sh
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# Verify that "morph edit" clones a chunk repository into a system branch.


set -eu

# Create system branch.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch newbranch

# Edit chunk.
cd newbranch/morphs
"$SRCDIR/scripts/test-morph" edit baserock:hello master

echo "Current branches, morphs:"
"$SRCDIR/scripts/run-git-in" "$DATADIR/workspace/newbranch/morphs" branch

echo "Current origin, morphs:"
"$SRCDIR/scripts/run-git-in" "$DATADIR/workspace/newbranch/morphs" \
    remote show origin | \
        sed 's,\(TMP/workspace/\.morph/cache/gits/file_\).*_,\1,g'

echo "Current branches, hello:"
"$SRCDIR/scripts/run-git-in" \
    "$DATADIR/workspace/newbranch/baserock:hello" branch

echo "Current origin, hello:"
"$SRCDIR/scripts/run-git-in" "$DATADIR/workspace/newbranch/baserock:hello" \
    remote show origin | \
        sed 's,\(TMP/workspace/\.morph/cache/gits/file_\).*_,\1,g'
