#!/bin/sh
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# Check that "morph merge" merges explicitly named repositories.


set -eu


# Create system branch.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch baserock:morphs newbranch

# Make a change to a chunk.
"$SRCDIR/scripts/test-morph" edit hello-system hello-stratum hello
cd newbranch/baserock:hello
touch newfile.txt
git add newfile.txt
git commit -m foo --quiet

# Merge changes to a new system branch.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" branch baserock:morphs otherbranch
cd otherbranch
"$SRCDIR/scripts/test-morph" edit hello-system hello-stratum hello
"$SRCDIR/scripts/test-morph" merge newbranch baserock:hello

# Check results.
cd baserock:hello
git status --short # make sure all changes are committed
ls newfile.txt # make sure the new file is there

