#!/bin/sh
#
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Check that 'morph tag example-tag' successfully creates a dangling
## commit and an annotated tag pointing to this commit.

set -eu

# Make sure the commits always have the same SHA1s.
. "$SRCDIR/scripts/fix-committer-info"

# Create a workspace and branch.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" checkout test:morphs master

# Tag the system branch.
"$SRCDIR/scripts/test-morph" tag example-tag -- -m Message

# Show the tag itself and its log. This allows to verify a couple of things,
# including that the commit and tag are created, that the commit message is
# set correctly and that all references are petrified.
"$SRCDIR/scripts/test-morph" foreach -- git show example-tag
"$SRCDIR/scripts/test-morph" foreach -- git log example-tag
