#!/bin/sh
# Copyright (C) 2012-2013  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# Add a second chunk to hello-stratum.

. "$SRCDIR/scripts/fix-committer-info"

create_chunk() {
    REPO="$1"
    NAME="$2"

    mkdir "$1"
    ln -s "$1" "$1.git"
    cd "$1"

    cat <<EOF > "$1/$2.morph"
build-system: dummy
kind: chunk
name: $2
EOF

    git init --quiet
    git add  .
    git commit --quiet -m "Initial commit"
}

create_chunk "$DATADIR/goodbye" "hello"

cd "$DATADIR/morphs"
cat <<EOF > hello-stratum.morph
name: hello-stratum
kind: stratum
chunks:
- build-depends: []
  name: hello
  ref: master
  repo: test:hello
- build-depends: []
  name: goodbye
  ref: master
  repo: test:goodbye
EOF

git commit -q --all -m "Add goodbye to hello-stratum"

cd "$DATADIR/workspace"
