#!/bin/sh
# Copyright (C) 2012-2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


# Add a second chunk to hello-stratum.

. "$SRCDIR/scripts/fix-committer-info"

create_chunk() {
    REPO="$1"
    NAME="$2"

    mkdir "$1"
    ln -s "$1" "$1.git"
    cd "$1"

    cat <<EOF > "$1/$2.morph"
build-system: dummy
kind: chunk
name: $2
EOF

    git init --quiet
    git add  .
    git commit --quiet -m "Initial commit"
}

create_chunk "$DATADIR/goodbye" "goodbye"

cd "$DATADIR/morphs"
cat <<EOF > hello-stratum.morph
name: hello-stratum
kind: stratum
chunks:
- name: hello
  repo: test:hello
  ref: master
  build-depends: []
  build-mode: bootstrap
  build-system: manual
- name: goodbye
  repo: test:goodbye
  ref: master
  build-depends: []
  build-mode: bootstrap
  build-system: manual
EOF

git commit -q --all -m "Add goodbye to hello-stratum"

cd "$DATADIR/workspace"
