#!/bin/sh
#
# Copyright (C) 2012,2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


## Check that 'morph show-system-branch' works even outside a branch
## if there only is one in the workspcae.

set -eu

# Create a workspace and a system branch.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch test:morphs first/branch

# Show the branch even when outside the branch.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" show-system-branch
