#!/bin/sh
#
# Copyright (C) 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Check that 'morph show-system-branch' shows the name of the
## current system branch correctly from various working directories.

set -eu

# Create a workspace and two system branches.
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch test:morphs first/branch
"$SRCDIR/scripts/test-morph" branch test:morphs second/branch

# Create a few subdirectories in the first branch.
mkdir -p "$DATADIR/workspace/first/branch/foo"
mkdir -p "$DATADIR/workspace/first/branch/bar"
mkdir -p "$DATADIR/workspace/first/branch/foo/bar/baz"

# Show the first branch when partially inside the branch.
cd "$DATADIR/workspace/first"
"$SRCDIR/scripts/test-morph" show-system-branch

# Show the first branch when inside the main branch directory.
cd "$DATADIR/workspace/first/branch"
"$SRCDIR/scripts/test-morph" show-system-branch

# Show the first branch when somewhere inside the branch.
cd "$DATADIR/workspace/first/branch/foo"
"$SRCDIR/scripts/test-morph" show-system-branch

# Show the first branch when somewhere else inside the branch.
cd "$DATADIR/workspace/first/branch/foo/bar/baz"
"$SRCDIR/scripts/test-morph" show-system-branch

# Show the second branch when partially inside the branch.
cd "$DATADIR/workspace/second"
"$SRCDIR/scripts/test-morph" show-system-branch

# Show the second branch when inside the main branch directory.
cd "$DATADIR/workspace/second/branch"
"$SRCDIR/scripts/test-morph" show-system-branch
