#!/bin/sh
#
# Copyright (C) 2011, 2012,2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


## 'morph status' within a workspace

set -eu

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init .
"$SRCDIR/scripts/test-morph" checkout test:morphs master
"$SRCDIR/scripts/test-morph" branch test:morphs a/b/c/d/e/foo
"$SRCDIR/scripts/test-morph" branch test:morphs a/b/c/d/e/bar
mkdir a/b/c/red-herring

"$SRCDIR/scripts/test-morph" status
