#!/bin/sh
# Copyright (C) 2011, 2012  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# 'morph status' within a branch

set -eu

. "$SRCDIR/scripts/setup-3rd-party-strata"

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" branch baserock:morphs test

# Make the branch have some interesting changes and pitfalls
cd test
"$SRCDIR/scripts/test-morph" edit hello-system stratum2 hello

cd baserock:stratum2-hello
git checkout -q master

cd ..
mkdir red-herring
cd red-herring
git init -q .

"$SRCDIR/scripts/test-morph" status
