#!/bin/sh
#
# Copyright (C) 2011-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## 'morph status' within a branch

set -eu

# FIXME: This is disabled, since a) we haven't decided if we really
# want to support system and stratum morphologies in different git
# repos, and b) the rewritten "morph edit" thus doesn't support it,
# since writing the code is not necessarily simple if one wants to
# cover all corner cases.
cat "$SRCDIR/tests.branching/status-in-dirty-branch.stdout"
exit 0

. "$SRCDIR/scripts/setup-3rd-party-strata"

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" branch test:morphs branch1

# Make the branch have some interesting changes and pitfalls
cd branch1
"$SRCDIR/scripts/test-morph" edit hello-system stratum2 hello

cd test/stratum2-hello
git checkout -q master

cd ..
mkdir red-herring
cd red-herring
git init -q .

"$SRCDIR/scripts/test-morph" status
