#!/bin/sh
#
# Copyright (C) 2012-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Do a complete workflow test, with strata outside the main morphologies
## repository.

# FIXME: We don't know if we want to support this, and the new "morph
# edit" doesn't support it yet, also due to time constraints.
exit 0

set -eu

. "$SRCDIR/scripts/setup-3rd-party-strata"

# Make a change to the system
# FIXME: we should try and build it, too
cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" branch test:morphs me/readme-fixes

# Edit one chunk
cd "me/readme-fixes"
"$SRCDIR/scripts/test-morph" edit hello
cd "$DATADIR/workspace/me/readme-fixes/test/stratum2-hello"
echo > README yoyoyo
git add README
git commit -m "Fix README in hello" --quiet

# Edit the other chunk too
"$SRCDIR/scripts/test-morph" edit hello
cd "$DATADIR/workspace/me/readme-fixes/test/stratum3-hello"
echo > README yoyoyo
git add README
git commit -m "Fix README in hello" --quiet

# Update the morphology repos
cd ../test/external-strata
git commit --quiet --all -m "Commit changes for system branch"

cd ../test/morphs
git commit --quiet --all -m "Commit changes for system branch"

# Merge our system branch into master
cd "$DATADIR/workspace"
cd master
"$SRCDIR/scripts/test-morph" merge me/readme-fixes

# Check the changes have appeared
cd test/morphs
[ $(git rev-parse HEAD) = $(git rev-parse master) ]

cd ../test/stratum2-hello
[ -e README ]
[ $(git rev-parse HEAD) = $(git rev-parse master) ]

cd ../test/stratum3-hello
[ -e README ]
[ $(git rev-parse HEAD) = $(git rev-parse master) ]
