#!/bin/sh
#
# Copyright (C) 2012,2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## Do a complete workflow test with Morph branching and merging.

set -eu

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" branch test:morphs me/readme-fix
"$SRCDIR/scripts/test-morph" edit hello-system hello-stratum hello
cd me/readme-fix/test/hello
echo > README yoyoyo
git add README
git commit -m "Fix README, yo!" --quiet

cd ../morphs
git commit --quiet --all -m "Commit changes for system branch"

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" checkout test:morphs master
cd master
"$SRCDIR/scripts/test-morph" merge me/readme-fix
