#!/bin/sh
#
# Copyright (C) 2012-2014  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

## If morphology kind differs between branches, it's a merge conflict

set -eu

cd "$DATADIR/workspace"
"$SRCDIR/scripts/test-morph" init
"$SRCDIR/scripts/test-morph" checkout test:morphs master
"$SRCDIR/scripts/test-morph" branch test:morphs test/unmergable

cd "$DATADIR/workspace/test/unmergable/test:morphs"
sed -ie 's/"kind": "stratum"/"kind": "chunk"/' hello-stratum.morph
git commit --quiet --all -m "Unmergeable because kind has changed"

cd "$DATADIR/workspace/master/test:morphs"
"$SRCDIR/scripts/test-morph" merge test/unmergable
