#!/bin/sh
# Copyright (C) 2012,2015  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

# Wrapper around morph for use by cmdtest tests. This does several things:
#
#   * simpler command lines for running morph, so that each test does not
#     need to add --no-default-config and other options every time
#   * replace temporary filenames ($DATADIR) in the output with a known
#     string ("TMP"), so that test output is deterministic

set -eu

if "$@" > "$DATADIR/stdout" 2> "$DATADIR/stderr"
then
    exit=0
else
    exit=1
fi

sed -i "s,$DATADIR,TMP,g" "$DATADIR/stdout" "$DATADIR/stderr"
cat "$DATADIR/stdout"
cat "$DATADIR/stderr" 1>&2

rm -f "$DATADIR/stdout" "$DATADIR/stderr"

exit "$exit"

