#!/bin/sh
# Copyright (C) 2012,2015  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

# Fix git committer info. By hardcoding all of this info we make sure that
# all of the commits we make during testing have reproducible commit SHA1s.

export GIT_AUTHOR_NAME=developer
export GIT_AUTHOR_EMAIL=developer@example.com
export GIT_AUTHOR_DATE="1343753514 +0000"
export GIT_COMMITTER_NAME=developer
export GIT_COMMITTER_EMAIL=developer@example.com
export GIT_COMMITTER_DATE="1343753514 +0000"
