#!/bin/sh
# Copyright (C) 2012-2013  Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# When sourced by scripts, if the python version is too old
# fake the output and exit.

if ! python --version 2>&1 | grep '^Python 2\.[78]' > /dev/null
then
    outpath="$(dirname "$0")/$(basename "$0" .script).stdout"
    errpath="$(dirname "$0")/$(basename "$0" .script).stderr"
    exitpath="$(dirname "$0")/$(basename "$0" .script).exit"
    if [ -r "$outpath" ]; then
        cat "$outpath"
    fi
    if [ -r "$errpath" ]; then
        cat "$errpath" >&2
    fi
    if [ -r "$exitpath" ]; then
        exit "$(cat "$exitpath")"
    else
        exit 0
    fi
fi
